apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    app: my-app

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
